#
# Setting limits for a particular namespace
#

apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-rq
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    limits.cpu: "10"

#
# kubectl get resourcequotas
#     No resources found.
#
# kubectl create -f 07-resource-quota.yml 
#     resourcequota/dev-rq created
#
# kubectl get resourcequotas --namespace dev
#     NAME     CREATED AT
#     dev-rq   2019-06-12T23:37:29Z
#
# kubectl describe resourcequota dev-rq --namespace dev
#     Name:         dev-rq
#     Namespace:    dev
#     Resource      Used  Hard
#     --------      ----  ----
#     limits.cpu    0     10
#     pods          0     10
#     requests.cpu  0     4
#